### ISSUE TITLE
Setup Github Pages

### ISSUE THREAD

**Issue by sgtlaggy** [AcksBerg/SPTRealismAmmoGraph#1]
Pages will provide an easy method of hosting this so every user doesn't need to download it.
All you should need to do is go to the repo's Settings -> Pages and set the Source to "Deploy from a branch."
I've set this up in my fork as an example, it can be found [here](https://sgtlaggy.github.io/SPTRealismAmmoGraph/).

**Comment by AcksBerg** [comment]
Thanks for the example, I did not see the issue until now. I make it when I am back home.
